services:
  hugo:
    image: hugomods/hugo:exts
    container_name: kaido-hugo-${VERSION:-1.0.0}
    volumes:
      - ./hugo:/src
      - hugo_public:/target
    environment:
      - HUGO_BASEURL=${HUGO_BASEURL}
      - HUGO_ENVIRONMENT=${HUGO_ENVIRONMENT}
    command: >
      server 
      --environment=production 
      --bind=0.0.0.0 
      --destination=/target 
      --minify 
      --watch 
      --disableFastRender 
      --forceSyncStatic 
      --baseURL=https://kaido.helenfit.com
      --appendPort=false
    networks:
      - kaido-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: kaido-nginx-${VERSION:-1.0.0}
    ports:
      - "${NGINX_PORT_HTTP:-80}:80"
      - "${NGINX_PORT_HTTPS:-443}:443"
    volumes:
      - hugo_public:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - certbot_certs:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot
      - nginx_logs:/var/log/nginx
    environment:
      - TZ=Asia/Taipei
    depends_on:
      - hugo
    restart: unless-stopped
    networks:
      - kaido-network
    command: >
      sh -c "if [ -L /var/log/nginx/access.log ]; then
               rm -f /var/log/nginx/access.log /var/log/nginx/error.log;
               touch /var/log/nginx/access.log /var/log/nginx/error.log;
             fi &&
             chown nginx:nginx /var/log/nginx/*.log 2>/dev/null || true &&
             nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    container_name: kaido-certbot-${VERSION:-1.0.0}
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - ./certbot:/scripts
    entrypoint:
      - /bin/sh
      - -c
    command: "trap 'exit 0' TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    networks:
      - kaido-network

volumes:
  hugo_public:
    name: kaido-hugo-public
  certbot_certs:
    name: kaido-certbot-certs
  certbot_www:
    name: kaido-certbot-www
  nginx_logs:
    name: kaido-nginx-logs

networks:
  kaido-network:
    name: kaido-network
    driver: bridge